#!/usr/bin/env bash

######################################
# Created By Golansho
#
# Date - 25/12/18
#
# Purpose : Printing hello world
#
# Ver : 1.0.0
#
######################################

set - x # For debuging purpose

echo '*hello world*'

